// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PrediCop.Infrastructure.Data;

#nullable disable

namespace PrediCop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629000001_AddCallDuration")]
    partial class AddCallDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // BuildTargetModel is used only when scaffolding new migrations.
            // The authoritative snapshot is AppDbContextModelSnapshot.cs.
        }
    }
}
